apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-local-pv-1
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/my-app-pv-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-local-pv-2
  labels:
    type: local
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data/myapp-pv-2
